language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.1
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.10
install:
  - pip install -q Django==$DJANGO
  - pip install -q django-nose==1.2
  - pip install -e .
script:
  - python runtests.py
